=== resace3/xml_to_dataframe/test.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="orders">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="order" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:int" name="bananas"/>
              <xs:element type="xs:int" name="apples"/>
              <xs:element type="xs:float" name="strawberries"/>
              <xs:element type="xs:float" name="price"/>
              <xs:element type="xs:float" name="tax"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== resace3/xml_to_dataframe/test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Document created with online XML Editor http://xmlgrid.net 2020/04/07 20:21:35  -->
   <orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://test.xsd">
         <order name="test attribute">
               <bananas>1</bananas>
               <apples>1</apples>
               <strawberries>2.7182818284</strawberries>
               <price>2.7182818284</price>
               <tax>2.7182818284</tax>
         </order>
         <order name="test attribute">
               <bananas>1</bananas>
               <apples>1</apples>
               <strawberries>2.7182818284</strawberries>
               <price>2.7182818284</price>
               <tax>2.7182818284</tax>
         </order>
         <order name="test attribute">
               <bananas>1</bananas>
               <apples>1</apples>
               <strawberries>2.7182818284</strawberries>
               <price>2.7182818284</price>
               <tax>2.7182818284</tax>
         </order>
         <order name="test attribute">
               <bananas>1</bananas>
               <apples>1</apples>
               <strawberries>2.7182818284</strawberries>
               <price>2.7182818284</price>
               <tax>2.7182818284</tax>
         </order>
         <order name="test attribute">
               <bananas>1</bananas>
               <apples>1</apples>
               <strawberries>2.7182818284</strawberries>
               <price>2.7182818284</price>
               <tax>2.7182818284</tax>
         </order>
         <order name="test attribute">
               <bananas>1</bananas>
               <apples>1</apples>
               <strawberries>2.7182818284</strawberries>
               <price>2.7182818284</price>
               <tax>2.7182818284</tax>
         </order>
         <order name="test attribute">
               <bananas>1</bananas>
               <apples>1</apples>
               <strawberries>2.7182818284</strawberries>
               <price>2.7182818284</price>
               <tax>2.7182818284</tax>
         </order>
 </orders>
